version: '3'

networks:
  intecwork:
    driver: bridge

volumes:
  content:
  ldap_db:
  ldap_config:
  postgres_data:

services:
  intectainment:
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    container_name: Intectainment

    ports:
      - "80:80"
    environment:
      - INTECTAINMENT_DB_URI=sqlite:///content/database.db
      - INTECTAINMENT_SECRET=Hallo

    volumes:
      - content:/Intectainment/Intectainment/content
    networks:
      - intecwork
    depends_on:
    - openldap
  
  openldap:
    image: osixia/openldap:latest
    ports:
      - 389:389
      - 636:636
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - intecwork
  
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
      - intecwork
  
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - openldap
    networks:
    - intecwork
  
  ldapadmin:
    image: osixia/phpldapadmin

    ports:
    - 6443:443

    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap://openldap

    networks:
    - intecwork
