version: '3'

networks:
  intecwork:
    driver: bridge

volumes:
  content:
  ldap_db:
  ldap_config:

services:
  intectainment:
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    container_name: Intectainment

    ports:
      - "80:80"
    environment:
      - INTECTAINMENT_DB_URI=sqlite:///content/database.db
      - INTECTAINMENT_SECRET=Hallo

    volumes:
      - content:/Intectainment/Intectainment/content
    networks:
      - intecwork
    depends_on:
    - openldap
  
  openldap:
    image: osixia/openldap:latest
    ports:
      - 389:389
      - 636:636
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - intecwork
  ldapadmin:
    image: osixia/phpldapadmin

    ports:
    - 6443:443

    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap://openldap

    networks:
    - intecwork
